apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    group: node-backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node-application
  template:
    metadata:
      labels: 
        name: node-application
    spec:
      containers:
        - name: node-app
          image: autob0t/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-env-map
                  key: folder
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc