apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: backend-app
spec:
  selector:
    name: node-application
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type:  LoadBalancer