apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: node-backend-app
spec:
  selector:
    app: node-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer