apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: backend-app
spec:
  selector:
    name: node-app
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer