apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api-app
          image: dheeraj1429/node-api-app:v1
          env:
            - name: APP_ADDRESS
              value: localhost:3000
        - name: node-client-app
          image: dheeraj1429/node-client-app     